version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mobleman_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mobleman
      POSTGRES_PASSWORD: mobleman_password
      POSTGRES_DB: mobleman_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 