[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
production.DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
production.PRISMA_BINARY_TARGET = "linux-musl"
production.PRISMA_CLI_BINARY_TARGETS = "linux-musl,linux-musl-openssl-1.1.x" 